### ISSUE TITLE
Percent (%) methods

### ISSUE THREAD

**Issue by Toasterbirb** [realQuartzi/Quartzified#6]
Add percent methods like
- Percent of
- Percent higher than
- Percent lower than
etc.

**Comment by realQuartzi** [comment]
Like basic Function
```
public static int GetPercent(int value, int total){
return ((value * 100) / total)
}
```

and
`getPercent(value, total) >= threshold ? true : false`

**Comment by realQuartzi** [comment]
Added with the Mathematics and Finance Update! 
:D
